// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXVENnlcNkfVOldWha2H43fDXgYxsiZI',
    appId: '1:1096266484738:web:d1978fa7a907a7e932eb1b',
    messagingSenderId: '1096266484738',
    projectId: 'medical-app-1800d',
    authDomain: 'medical-app-1800d.firebaseapp.com',
    storageBucket: 'medical-app-1800d.appspot.com',
    measurementId: 'G-3KQ95Q0T28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxqmytXHcJvfHQYxzBCMnwuj8jaS8Wy8',
    appId: '1:1096266484738:android:01b89783fa9afeb332eb1b',
    messagingSenderId: '1096266484738',
    projectId: 'medical-app-1800d',
    storageBucket: 'medical-app-1800d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAzLVmP9Vt6o7MzTdbAZzG5quylnr3i8',
    appId: '1:1096266484738:ios:75fe9c72e7eced8732eb1b',
    messagingSenderId: '1096266484738',
    projectId: 'medical-app-1800d',
    storageBucket: 'medical-app-1800d.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAzLVmP9Vt6o7MzTdbAZzG5quylnr3i8',
    appId: '1:1096266484738:ios:75fe9c72e7eced8732eb1b',
    messagingSenderId: '1096266484738',
    projectId: 'medical-app-1800d',
    storageBucket: 'medical-app-1800d.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXVENnlcNkfVOldWha2H43fDXgYxsiZI',
    appId: '1:1096266484738:web:9883f5cb11b0670332eb1b',
    messagingSenderId: '1096266484738',
    projectId: 'medical-app-1800d',
    authDomain: 'medical-app-1800d.firebaseapp.com',
    storageBucket: 'medical-app-1800d.appspot.com',
    measurementId: 'G-RLYBQMTYQX',
  );
}
